version: '3'

services:

  backend:
    container_name: backend
    image: sskovgaard90/backend

  frontend:
    container_name: frontend
    image: sskovgaard90/frontend
    environment:
      - BACKEND_DNS=backend
    ports:
      - 8080:8080